ackermann_mux:
  ros__parameters:
    topics:
      ebrake:
        topic   : ebrake
        timeout : 0.5
        priority: 3
      navigation:
        topic   : drive
        timeout : 0.2
        priority: 2
      joystick:
        topic   : teleop
        timeout : 0.2
        priority: 1
