# Modify this file to fix servo issues
/**:
  # general parameters shared by all vesc-related nodes
  ros__parameters:
    # erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
    speed_to_erpm_gain: 4600.0
    speed_to_erpm_offset: 0.0

    # servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
    steering_angle_to_servo_gain: -0.696
    steering_angle_to_servo_offset: 0.475 # centre position found by trial and error

    port: /dev/sensors/vesc
    duty_cycle_min: 0.0
    duty_cycle_max: 0.0
    current_min: 0.0
    current_max: 100.0
    brake_min: -300000.0
    brake_max: 300000.0
    speed_min: -300000.0
    speed_max: 300000.0
    position_min: 0.0
    position_max: 0.0

    # LEFT
    servo_min: 0.10 # corresponds to max left steering clipping  
      # turning radius left is 1.1 m 
      # given wheelbase of 0.33 m, this means max left steering angle is 0.56 rad

    # RIGHT
    servo_max: 0.85 # corresponds to max right steering clipping
      # turning radius right is 1.2 m
      # given wheelbase of 0.33m, this means max right steering angle is 0.52 rad

# No longer needed, all parameters are shared
# ackermann_to_vesc_node:
#   ros__parameters:

vesc_to_odom_node:
  ros__parameters:
    odom_frame: odom
    base_frame: base_link
    # publish odom to base link tf
    publish_tf: true
    use_servo_cmd_to_calc_angular_velocity: true
    # car wheelbase is about 33 cm
    wheelbase: .33

# No longer needed, all parameters are shared
# vesc_driver:
#   ros__parameters:

throttle_interpolator:
  ros__parameters:
    rpm_input_topic: commands/motor/unsmoothed_speed
    rpm_output_topic: commands/motor/speed
    servo_input_topic: commands/servo/unsmoothed_position
    servo_output_topic: commands/servo/position

    # servo smoother - limits acceleration and smooths anything above limit
    max_acceleration: 2.5 # meters/second^2
    throttle_smoother_rate: 75.0 # messages/sec
    # servo smoother - limits rotation speed and smooths anything above limit
    max_servo_speed: 3.2 # radians/second
    servo_smoother_rate: 75.0 # messages/sec